name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the `main` branch
  pull_request:
    branches:
      - main  # Optional: Deploy when a PR is merged to `main`
  workflow_dispatch:  # Allow manual trigger via GitHub UI or API

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH into remote server
        run: |
          sshpass -p ${{ secrets.SSH_PASSPHRASE }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Any command you want to run remotely
          echo "Connected successfully"
          sudo ls -ltr
          EOF
