name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the `main` branch
  pull_request:
    branches:
      - main  # Optional: Deploy when a PR is merged to `main`
  workflow_dispatch:  # Allow manual trigger via GitHub UI or API

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH into remote server
        run: |
          sshpass -p ${{ secrets.SSH_PASSPHRASE }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Any command you want to run remotely
          echo "Connected successfully"
          sudo cp -rf /var/www/release/current /var/www/release/backup/$(date +\%Y\%m\%d\%H\%M\%S)
          cd /var/www/laravel
          git pull origin master  # Pull latest changes from the main branch
          composer install --no-dev --optimize-autoloader  # Install production dependencies
          php artisan migrate --force  # Run database migrations
          php artisan config:cache  # Cache the configuration
          php artisan route:cache  # Cache routes
          php artisan view:cache  # Cache views
          sudo systemctl restart nginx # Reload server (if using Apache) or reload nginx, etc.
          EOF
