name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the `main` branch
  pull_request:
    branches:
      - main  # Optional: Deploy when a PR is merged to `main`
  workflow_dispatch:  # Allow manual trigger via GitHub UI or API

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH to connect to EC2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Step 3: Deploy to EC2 after approval
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
           sudo ls -ltr
          EOF
