name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: secret_lab_test
          MYSQL_USER: root
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=30s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
    
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Dump Autoload
      run: composer dump-autoload --optimize

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Set up .env file for MySQL
      run: |
        cp .env.example .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=secret_lab_test" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=secret" >> .env

    - name: Wait for MySQL to be ready
      run: |
        until mysql -h 127.0.0.1 -u root -psecret -e "show databases"; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Execute tests (Unit and Feature tests)
      run: php artisan test
